import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import PerformanceBlock from "../../components/PerformanceBlock";
import Navbar from "../../components/Navbar";
import SeasonStats from "../../components/SeasonStats";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar/>

        <div className={styles.container}>

        

          <div className={styles.subContainer}>
            <ul>
              <li>
                <div className={styles.containerLeft}>
                  <h2>Recent Performances</h2>
                  <ul>
                    <li><PerformanceBlock/></li>

                  </ul>
                </div>  
              </li>
              <li>
                <div className={styles.containerCenter}>
                  Center block
                  </div>
                </li>
              <li>
              <SeasonStats/>
             
              </li>
            </ul>
          </div>


        </div>
      </div>
    </>
  );
}
