import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import PerformanceBlock from "../../components/PerformanceBlock";
import Navbar from "../../components/Navbar";
import SeasonStats from "../../components/SeasonStats";

import matchForm from "@/styles/addEvent.module.css"

const attributes = ["1 V 1 Defending", "Ariel Duels", "Communication", "Ariel Duels",
  "Goal(s)", "Assist(s)", "1 V 1 Attacking", "Progressive passing", "Add+"
]
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar/>

        <div className={styles.container}>

        

          <div className={styles.subContainer}>
            <ul>
              <li>
                <div className={styles.containerLeft}>
                  <h2>Recent Performances</h2>
                  <ul>
                    <li><PerformanceBlock 
                    opponent={"Raynes Park Vale"}
                    matchRating={9.0}
                    competition={"League"}
                    minutesPlayed={90}
                    conditionAfter={"Good"}/>
                    </li>
                    <li><PerformanceBlock 
                    opponent={"Raynes Park Vale"}
                    matchRating={9.0}
                    competition={"League"}
                    minutesPlayed={90}
                    conditionAfter={"Good"}/>
                    </li>
                    <li><PerformanceBlock 
                    opponent={"Raynes Park Vale"}
                    matchRating={9.0}
                    competition={"League"}
                    minutesPlayed={90}
                    conditionAfter={"Good"}/>
                    </li>

                  </ul>
                </div>  
              </li>
              <li>
                <div className={styles.containerCenter}>
                  Center block
                  </div>
                </li>
              <li>
              <SeasonStats/>



             
              </li>
            </ul>
          </div>

          <div className={matchForm.addEventPane}>
            <h2>Match Review</h2>
            <form className={matchForm.addMatchBox}>
              <label className={matchForm.labels}>Opponent:</label>
              <input type="input" name = "opponent" className={matchForm.opponentBox}/>

              <div className={matchForm.minsAndConditionBox}>
                <div>
                <label className={matchForm.labels}>Minutes Played:</label>
                <input type="input" name="minutesPlayed" />
                </div>
              <div>

              <label className={matchForm.labels}>Condition:</label>
              <input type="input" name="condition"/>
            </div>
          </div>

          <label className={matchForm.labels}>How did you perfom?</label>
          <textarea className={matchForm.matchDescription}/>


<div className={matchForm.attributeContainer}>
      <label className={matchForm.labels}>Select 4 areas you 
        excelled in during the game</label>
<ul className={matchForm.attributeList}>
{(attributes).map((item, index) => (
<li key={index} onClick={() => showTicketWindowPane(item)}>
          <div className={matchForm.attributeBlock}>
            <p>{item}</p>
          </div>
           </li>
       ))}
   </ul>
</div>


   
            </form>


          </div>
        </div>
      </div>
    </>
  );
}
